FROM ubuntu:22.04 as base

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y hello \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

FROM ubuntu:22.04
COPY --from=base /usr/bin/hello /usr/bin/hello
